### ISSUE TITLE
Specify the Package Manager

### ISSUE THREAD

**Issue by vzrenggamani** [gdsc-um/homesite-refactor#9]
## Description
Pada repository ini, terdapat dua package manager yang digunakan secara bebarengan yang berakibat pada tersedianya dua `lockfile` dari dua package manager yang berbeda. Hal ini dapat menyebabkan adanya package collision pada tahap build ataupun pada alur kerja kolaborasi meskipun dependency sudah di lock melalui `package.json`

## Expected Behavior
1. Gunakan satu dependency manager untuk seluruh kolaborator. Gunakan PNPM atau NPM saja
2. Kunci versi dependency manager pada sebuah versi mayor, plese read https://stackoverflow.com/questions/71747609/how-to-specify-packagemanager-in-package-json and https://docs.npmjs.com/cli/v10/configuring-npm/package-json#devengines

## Actual Behavior
1. terdapat dua lockfile `package-lock.json` dan [pnpm-lock.yaml](https://github.com/gdsc-um/homesite-refactor/blob/main/pnpm-lock.yaml)

## Possible Fix
1. Tentukan package manager yang digunakan
2. Hapus salah satu lockfile dan kunci versi package manager dan devengine pada package.json
3. Migrasikan perubahan tersebut untuk semua branch development

CC: @gdsc-um/web-dev

**Comment by Archiruz** [comment]
Noted, rencana kami akan menggunakan pnpm untuk kedepannya dengan pertimbangan karena lebih cepat

CC: @Alvalens untuk PR kedepannya di review kalau masih ada yang commit package-lock.json mohon direject dan suruh fix

**Comment by vzrenggamani** [comment]
Fixed in 996c89fb00579bf0c0da31cdf0d22f6d6cdae8c1
